name = "GamersReloaded"
author = "Gamers"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6710a85b96d8822d6f8e5b211e6be6e496f9e6ec04d79b2205b0b3998e3d80f4"

[versions]
forge = "40.1.84"
minecraft = "1.18.2"
