name = "ForgePackBase"
author = "Den4enko"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "794ed038676cc38a24f4debda94e9054f8ee61bf2215da848a28d7b9649669ce"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
