name = "ForgePackBase"
author = "Den4enko"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09c2f6a17cbf3b99a02d08b0670eb05154433af48a88cc6854d1334f9d35914e"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
