name = "GamersReloaded"
author = "Gamers"
version = "1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe71693746edc45c509b5f1862cc96fc9628054a2f1cd3faeab6291f413d85ee"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
